Rails:
  Enabled: true
AllCops:
  Exclude:
    - "db/**/*"
    - "vendor/**/*"

Style/Documentation:
  Exclude:
    - "config/application.rb"
    - "db/**/*"
    - "app/controllers/**/*"
    - "app/queries/**/*"
    - "app/models/**/*"
    - "app/serializers/**/*"
    - "app/services/**/*"
    - "app/validators/**/*"
