AllCops:
  Rails:
    Enabled: true
  Exclude:
    - "db/**/*"
    - "vendor/**/*"

Style/Documentation:
  Exclude:
    - "config/application.rb"
    - "db/**/*"
    - "app/models/**/*"
    - "app/controllers/**/*"
    - "app/serializers/**/*"
    - "app/validators/**/*"
