AllCops:
  RunRailsCops: true
  Exclude:
    - "db/schema.rb"
    - "vendor/**/*"

Style/Documentation:
  Exclude:
    - "config/application.rb"
    - "db/**/*"
    - "app/models/**/*"
    - "app/controllers/**/*"
    - "app/serializers/**/*"
